//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.02 at 05:06:50 PM WAT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://sample-xsd.org/sample/process", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.sample_xsd.sample.process;
