//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.02 at 05:06:50 PM WAT 
//


package org.sample_xsd.sample.process;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SampleProcess complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SampleProcess">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="start" type="{http://sample-xsd.org/sample/process}Execution"/>
 *         &lt;element name="before" type="{http://sample-xsd.org/sample/process}Execution" minOccurs="0"/>
 *         &lt;element name="execution" type="{http://sample-xsd.org/sample/process}Execution"/>
 *         &lt;element name="after" type="{http://sample-xsd.org/sample/process}Execution" minOccurs="0"/>
 *         &lt;element name="end" type="{http://sample-xsd.org/sample/process}Execution"/>
 *         &lt;element name="hook" type="{http://sample-xsd.org/sample/process}Hook" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="key" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SampleProcess", propOrder = {
    "start",
    "before",
    "execution",
    "after",
    "end",
    "hook"
})
public class SampleProcess {

    @XmlElement(required = true)
    protected Execution start;
    protected Execution before;
    @XmlElement(required = true)
    protected Execution execution;
    protected Execution after;
    @XmlElement(required = true)
    protected Execution end;
    protected Hook hook;
    @XmlAttribute(name = "key")
    protected String key;
    @XmlAttribute(name = "name")
    protected String name;

    /**
     * Gets the value of the start property.
     * 
     * @return
     *     possible object is
     *     {@link Execution }
     *     
     */
    public Execution getStart() {
        return start;
    }

    /**
     * Sets the value of the start property.
     * 
     * @param value
     *     allowed object is
     *     {@link Execution }
     *     
     */
    public void setStart(Execution value) {
        this.start = value;
    }

    /**
     * Gets the value of the before property.
     * 
     * @return
     *     possible object is
     *     {@link Execution }
     *     
     */
    public Execution getBefore() {
        return before;
    }

    /**
     * Sets the value of the before property.
     * 
     * @param value
     *     allowed object is
     *     {@link Execution }
     *     
     */
    public void setBefore(Execution value) {
        this.before = value;
    }

    /**
     * Gets the value of the execution property.
     * 
     * @return
     *     possible object is
     *     {@link Execution }
     *     
     */
    public Execution getExecution() {
        return execution;
    }

    /**
     * Sets the value of the execution property.
     * 
     * @param value
     *     allowed object is
     *     {@link Execution }
     *     
     */
    public void setExecution(Execution value) {
        this.execution = value;
    }

    /**
     * Gets the value of the after property.
     * 
     * @return
     *     possible object is
     *     {@link Execution }
     *     
     */
    public Execution getAfter() {
        return after;
    }

    /**
     * Sets the value of the after property.
     * 
     * @param value
     *     allowed object is
     *     {@link Execution }
     *     
     */
    public void setAfter(Execution value) {
        this.after = value;
    }

    /**
     * Gets the value of the end property.
     * 
     * @return
     *     possible object is
     *     {@link Execution }
     *     
     */
    public Execution getEnd() {
        return end;
    }

    /**
     * Sets the value of the end property.
     * 
     * @param value
     *     allowed object is
     *     {@link Execution }
     *     
     */
    public void setEnd(Execution value) {
        this.end = value;
    }

    /**
     * Gets the value of the hook property.
     * 
     * @return
     *     possible object is
     *     {@link Hook }
     *     
     */
    public Hook getHook() {
        return hook;
    }

    /**
     * Sets the value of the hook property.
     * 
     * @param value
     *     allowed object is
     *     {@link Hook }
     *     
     */
    public void setHook(Hook value) {
        this.hook = value;
    }

    /**
     * Gets the value of the key property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKey(String value) {
        this.key = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
